############################################################################
# Contest 2026 team 423 v4l2cap - Makefile
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = v4l2cap
PRIORITY  = SCHED_PRIORITY_DEFAULT
STACKSIZE = 8192
MODULE    = $(CONFIG_LVX_USE_DEMO_CONTEST2026_423_V4L2CAP)

MAINSRC = v4l2cap_main.c

include $(APPDIR)/Application.mk
