############################################################################
# Contest 2026 team 423 ampctl - Makefile
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = ampctl
PRIORITY  = SCHED_PRIORITY_DEFAULT
STACKSIZE = 8192
MODULE    = $(CONFIG_LVX_USE_DEMO_CONTEST2026_423_AMPCTL)

MAINSRC = ampctl_main.c

include $(APPDIR)/Application.mk
