############################################################################
# packages/demos/contest2026_423_k7diag/Makefile
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = k7diag
PRIORITY  = SCHED_PRIORITY_DEFAULT
STACKSIZE = 8192
MODULE    = $(CONFIG_LVX_USE_DEMO_CONTEST2026_423_K7DIAG)

MAINSRC = k7diag_main.c

include $(APPDIR)/Application.mk
