############################################################################
# Contest 2026 team 423 bt - Makefile
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = bt
PRIORITY  = SCHED_PRIORITY_DEFAULT
STACKSIZE = 4096
MODULE    = $(CONFIG_LVX_USE_DEMO_CONTEST2026_423_BT)

MAINSRC = bt_main.c

include $(APPDIR)/Application.mk
