############################################################################
# Contest 2026 team 423 hdmi - Makefile
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = hdmi
PRIORITY  = SCHED_PRIORITY_DEFAULT
STACKSIZE = 4096
MODULE    = $(CONFIG_LVX_USE_DEMO_CONTEST2026_423_HDMI)

MAINSRC = hdmi_main.c

include $(APPDIR)/Application.mk
