############################################################################
# Contest 2026 team 423 spi selftest - Makefile
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = spi_selftest
PRIORITY  = SCHED_PRIORITY_DEFAULT
STACKSIZE = 4096
MODULE    = $(CONFIG_LVX_USE_DEMO_CONTEST2026_423_SPI_SELFTEST)

MAINSRC = spi_selftest_main.c

include $(APPDIR)/Application.mk
