############################################################################
# Contest 2026 team 423 cam - Makefile
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = cam
PRIORITY  = SCHED_PRIORITY_DEFAULT
STACKSIZE = 4096
MODULE    = $(CONFIG_LVX_USE_DEMO_CONTEST2026_423_CAM)

MAINSRC = cam_main.c

include $(APPDIR)/Application.mk
