############################################################################
# Contest 2026 team 423 mic - Makefile
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = mic
PRIORITY  = SCHED_PRIORITY_DEFAULT
STACKSIZE = 8192
MODULE    = $(CONFIG_LVX_USE_DEMO_CONTEST2026_423_MIC)

MAINSRC = mic_main.c

include $(APPDIR)/Application.mk
