############################################################################
# packages/demos/contest2026_423_kickpi_ui/Makefile
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = kickpi_ui
PRIORITY  = $(CONFIG_LVX_DEMO_CONTEST2026_423_KICKPI_UI_PRIORITY)
STACKSIZE = $(CONFIG_LVX_DEMO_CONTEST2026_423_KICKPI_UI_STACKSIZE)
MODULE    = $(CONFIG_LVX_USE_DEMO_CONTEST2026_423_KICKPI_UI)

MAINSRC = kickpi_ui_main.c

include $(APPDIR)/Application.mk
